# Generated by Django 5.0.3 on 2024-04-15 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='zonasUMAPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la zona')),
                ('nombre_bomba', models.CharField(max_length=50, verbose_name='Nombre de la bomba')),
                ('activo', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Zonas de Distribución UMAPS',
            },
        ),
        migrations.CreateModel(
            name='perfilEmpleadosUMAPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Perfil de Usuario UMAPS')),
            ],
            options={
                'verbose_name_plural': 'Perfil de Empleados UMAPS',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='registroActividadUMAPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activacion', models.BooleanField(default=False)),
                ('tiempo', models.DateTimeField(auto_now=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.zonasumaps')),
            ],
            options={
                'verbose_name_plural': 'Registro de Actividad de Bombas en Zonas UMAPS',
            },
        ),
        migrations.CreateModel(
            name='intervaloCalendarioUMAPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaInicio', models.DateTimeField(verbose_name='Hora de apertura bomba')),
                ('horaFinal', models.DateTimeField(verbose_name='Hora de cierre bomba')),
                ('responsable', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='miapp.perfilempleadosumaps', verbose_name='Responsable')),
                ('zona', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='miapp.zonasumaps', verbose_name='Zona')),
            ],
            options={
                'verbose_name_plural': 'Intervalo de Calendario Zonas UMAPS',
            },
        ),
    ]
